# create namespace 
apiVersion: v1
kind: Namespace
metadata:
  name: app-space
---
# create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: app-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: aws_account_id.dkr.ecr.aws_region.amazonaws.com/ecr_repo_name:myapp
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
