name: Deploy to EKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_LINK }}

      - name: Build and Push Docker Image
        run: |
          docker build -t myapp ./app/
          docker tag myapp:latest ${{ secrets.AWS_ECR_REPO }}:myapp
          docker push ${{ secrets.AWS_ECR_REPO }}:myapp

      # - name: Update kubeconfig
      #   run: |
      #     aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name particle41_eks

      # - name: Deploy to EKS
      #   run: |
      #     kubectl apply -f k8s/
