name: Deploy to EKS

on:
  push:
    branches: [main]
  # input for terraform apply or destroy
  workflow_dispatch:
    inputs:
      action:
        description: "Specify the Terraform action: apply or destroy"
        required: true
        default: "apply"

jobs:
  # terraform apply/destroy
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    outputs:
      AWS_ECR_REPO_NAME : ${{ steps.export.outputs.AWS_ECR_REPO_NAME }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: true
        terraform_version: 1.6.6

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Execute Terraform Action
      run: |
        if [ "${{ github.event.inputs.action }}" == "destroy" ]; then
          terraform destroy -auto-approve
        else
          terraform apply -auto-approve
        fi
    
    - name: Export Terraform outputs
      id: export 
      run: |
        REPO_NAME=$(terraform output -raw AWS_ECR_REPO_NAME | cut -d: -f1)
        echo "AWS_ECR_REPO_NAME=$REPO_NAME" >> "$GITHUB_OUTPUT"
        ACCOUNT_ID=$(terraform output -raw AWS_ACCOUNT_ID | cut -d: -f1)
        echo "AWS_ACCOUNT_ID=$ACCOUNT_ID" >> "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
    needs: terraform
    steps:

      - name: Print Terraform Output
        run: | 
          echo "AWS_ECR_REPO_NAME : ${{ needs.terraform.outputs.AWS_ECR_REPO_NAME }}"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $(needs.terraform.outputs.AWS_ECR_REPO_URL | cut -d/ f1)

      - name: Build and Push Docker Image
        run: |
          docker build -t myapp ./app/
          docker tag myapp:latest ${{ needs.terraform.outputs.AWS_ECR_REPO_URL }}:myapp
          docker push ${{ needs.terraform.outputs.AWS_ECR_REPO_URL }}:myapp

      # - name: Update kubeconfig
      #   run: |
      #     export cluster_name=${{ AWS_EKS_CLUSTER_NAME}}
      #     export vpc_id=$(aws eks describe-cluster --name $cluster_name --query "cluster.resourcesVpcConfig.vpcId" --output text)
      #     export aws_account_id = $(aws eks describe-cluster --name $cluster_name --query "cluster.arn" --output text  | cut -d: -f5)
          
      #     echo "cluster_name : $cluster_name"
      #     echo "vpc_id : $vpc_id"
      #     echo "aws_account_id : $aws_account_id"

      #     aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.AWS_EKS_NAME }}
      #     eksctl utils associate-iam-oidc-provider --cluster $cluster_name --approve

      #     eksctl create iamserviceaccount --cluster=$cluster_name --namespace=kube-system --name=aws-alb-controller --role-name ALBControllerIAMRole --attach-policy-arn=arn:aws:iam::$aws_account_id:policy/ALBControllerIAMPolicy --override-existing-serviceaccounts  --region ${{ secrets.AWS_REGION }} --approve

      #     helm repo add eks https://aws.github.io/eks-charts

      #     helm repo update eks 

      #     helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=particle41-eks --set serviceAccount.create=false --set serviceAccount.name=aws-alb-controller --set region=us-east-1 --set vpcId=$vpc_id

      # - name: Deploy to EKS
      #   run: |
      #     kubectl apply -f k8s/
